server:
  port: 8080
spring:
  application:
    #应用的名称，可选
    name: reggie_zzh
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      time-between-eviction-runs-millis: 300000 #创建的连接在长时间得不到调用后会报错，
  mail:
    host: smtp.qq.com
    username: 2805753067@qq.com
    password: pcdvqqnxtwdfdehi
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-value: 1
      logic-not-delete-value: 0

regger:
  path: D:\code\project\reggie_zzh\img\

